[package]
authors = ["Thomas Heck <t@b128.net>"]
name = "vtree_html"
version = "0.0.0"
build = "build.rs"

[dependencies]
vtree = { path = "../vtree" }
vtree_macros = { path = "../vtree/vtree_macros" }
