[package]
authors = ["Thomas Heck <t@b128.net>"]
name = "vtree-html"
version = "0.1.0"
build = "build.rs"

[dependencies]
vtree = { path = "../vtree/vtree" }
vtree_macros = { path = "../vtree/vtree_macros" }
